# 2024.01.15

## <Collaborative work>

### 🌟Collaborative

## <Personal Work>

### ⛄Nayeon

- melanoma_repetition Update
    
    코드 확인은 Ensemble-Kernel repositories 
    
    - dataframe에 append 사용 시 발생하는  error 수정
        - 최종 결과를 확인할 때 기존에는 append를 사용하여 결과를 모두 저장했는데 python 3.10.10에서는 error가 발생하는 것을 확인→loc로 문법 변경
        
        ```python
        kernel_type = 'ensemble_cox'
        
        for i in range(100):
            #variables = all_results['remaining_variables'][i]
            variables = eval(pd.read_csv("melanoma_cox_remaining_variables.csv")['variable'][i])
        
            df_onehot_re = df_onehot[variables]
            
            x_train, x_test, target_train, target_test = split_data(df_onehot_re, randomState = random_state[i])
        
            y_train = prepare_response_variable(target_train)
            y_test = prepare_response_variable(target_test)
        
            results = c_index_kernel_type(x_train, y_train, x_test, y_test, param_grid, param_space, cv, keywords = ['Age', 'Sex'], type = kernel_type)
            
            #ensemble_cox_results = ensemble_cox_results.append({"train_C_index":results[0],"test_C_index":results[1]}, ignore_index=True)
            ensemble_cox_results.loc[i] = [results[0], results[1]]
        
        ensemble_cox_results.to_csv("melanoma_cox_cox.csv", index = False, encoding = 'cp949')
        ```
